import { Command } from 'commander'
import { check, inspect, formatInspectReport } from '../../compiler/index.js'

export const checkCommand = new Command('check')
  .argument('<file>', 'path to .rcl source file')
  .option('--strict', 'treat warnings as errors')
  .option('--format <fmt>', 'output format: text (default) or json')
  .option('--inspect', 'show DATA symbols generated by LOAD FROM before type-checking')
  .description('Type-check a .rcl file without compiling — reports all errors and warnings')
  .addHelpText('after', `
  Tip: run with --inspect before writing DISPLAY statements to see every DATA
  symbol (name, PIC type, group shape) generated by LOAD FROM directives.`)
  .action((file: string, options: { strict?: boolean; format?: string; inspect?: boolean }) => {
    // ── --inspect: print LOAD FROM shape report then exit ──
    if (options.inspect) {
      const report = inspect(file)
      process.stdout.write(formatInspectReport(report) + '\n')
      process.exit(report.ok ? 0 : 1)
      return
    }

    const formatJson = options.format === 'json'
    const result = check(file, { strict: options.strict, formatJson })

    if (result.ok) {
      if (!formatJson) {
        console.log(`\n  ✓  ${result.inputPath}\n`)
      }
      // Exit 2 — warnings present but no errors
      if (result.warnings) process.exit(2)
    } else {
      // Exit 1 — errors present
      process.exit(1)
    }
  })
